### ISSUE TITLE
Deciding on Python code style

### ISSUE THREAD

**Issue by BigRoy** [BigRoy/fusionless#3]
The **fusionscript** packages tries to wrap all of Fusion's coding functionality in a more Pythonic manner. With that in mind I've been wrapping the methods and classes in the **PEP08** code style, even though Fusion uses UpperCamelCase functions.

I just wanted to check here if anyone has anything against rewriting it so it's more Pythonic and stepping away from how Fusion does it internally. Or would we rather stick with Fusion's code style even though it's far from good-looking in terms of Python code?
### Example

**Fusion**

``` python

class Comp(object):
    def GetAttrs(self):
        pass
```

**More Pythonic**

``` python

class Comp(object):
    def get_attrs(self):
        pass
```

**Comment by mottosso** [comment]
+1 for PEP08

**Comment by ftouvet** [comment]
+1 too

**Comment by BigRoy** [comment]
Cool, sticking to that. Closing this.
