### ISSUE TITLE
Comp FileName and saving

### ISSUE THREAD

**Issue by LarsCawley** [BigRoy/fusionless#7]
In a pipeline script that sets the save path for a comp, I'm trying the same syntax as setting other attributes, but the attribute doesn't get set.  In the script I am porting to Fusion/fusionless from Nuke the file path gets set and the user warned if the file already exists, after which they can overwrite it, or save a different version/name.

```
import fusionless as fu
cmp = fu.Comp()
cmp.set_attr('COMPS_FileName','C:\Temp\Monkey_v001.comp')
if foo == True:
    cmp.save()
```

I can script my way around the existing behaviour, but I thought I would let you know what I am trying to do.
In a related note, I see that I have a few options for saving comps here.  At first I was surprised that the fu.Comp().**save**() method didn't take a file path argument.
In this case the fusionscript version is pretty straight forward
comp.**Save**('C:\Temp\Monkeyhead_v001.comp')
and I see that this works too
fu.Comp().**Save**("C:\Temp\Monkey_v002.comp")

**Comment by BigRoy** [comment]
Ah yes, the fusionless version should be taking an argument as well then. 

Nice catch! Should be really easy. Might get to this in a couple of hours.

**Comment by BigRoy** [comment]
Reopening this as the `filename ()` method is  still to be implemented.
